name: epub
version: 3.0.0
author: Colin Nelson <colin@orthros.dev>
description: Epub Parser for Dart. Suitable for use on the Server, the Web, or in Flutter
homepage: https://github.com/orthros/dart-epub
environment:
  sdk: ">=2.14.0 <3.0.0"
dependencies:
  async: ">=1.8.0 <3.0.0"
  archive: ^3.1.2
  xml: ">=2.6.0 <6.0.0"
  image: ^3.1.1
dev_dependencies:
  test: ^1.20.1
  path: ^1.8.1
